CoreLeaveSystem/Controllers/VacationRequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using CoreLeaveSystem.Contracts;
using CoreLeaveSystem.Data;
using CoreLeaveSystem.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CoreLeaveSystem.Controllers
{
    [Authorize]
    public class VacationRequestController : Controller
    {
        private readonly IVacationRequestRepository _requestrepo;
        private readonly IVacationTypeRepository _typerepo;
        private readonly IVacationAllocationRepository _allocationrepo;
        private readonly IMapper _mapper;
        private readonly UserManager<Employee> _userManager;

        public VacationRequestController(IVacationRequestRepository requestrepo, IMapper mapper, UserManager<Employee> userManager, IVacationTypeRepository typerepo, IVacationAllocationRepository allocationrepo )
        {
            _requestrepo = requestrepo;
            _mapper = mapper;
            _userManager = userManager;
            _typerepo = typerepo;
            _allocationrepo = allocationrepo;
        }

        [Authorize(Roles = "Administrator")]
        // GET: VacationRequestController
        public async Task<ActionResult> Index()
        {
            var vacationRequests = await _requestrepo.FindAll();
            var vacationRequestsModel = _mapper.Map<List<VacationRequestVM>>(vacationRequests);
            var model = new AdminVacationRequestViewVM
            {
                TotalRequests = vacationRequestsModel.Count,
                ApprovedRequests = vacationRequestsModel.Count(q => q.Approved == true),
                PendingRequests = vacationRequestsModel.Count(q => q.Approved == null),
                RejectedRequests = vacationRequestsModel.Count(q => q.Approved == false),
                VacationRequests = vacationRequestsModel
            };
            return View(model);
        }

        // GET: VacationRequestController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var vacationrequest = await _requestrepo.FindById(id);
            var model = _mapper.Map<VacationRequestVM>(vacationrequest);

            return View(model);
        }

        public async Task<ActionResult> ApproveRequest(int id)
        {

            try
            {
                var user = await _userManager.GetUserAsync(User);
                var vacationRequest = await _requestrepo.FindById(id);
                var employeeid = vacationRequest.RequestingEmployeeId;
                var vacationtypeId = vacationRequest.VacationTypeId;
                var allocation = await _allocationrepo.GetVacationAllocationsByEmployeeAndType(employeeid,vacationtypeId);
                int daysRequested = (int)(vacationRequest.EndDate - vacationRequest.StartDate).TotalDays;
                // allocation.NumberOfDays = allocation.NumberOfDays - daysRequested; Alternative Way
                allocation.NumberOfDays -= daysRequested;

                vacationRequest.Approved = true;
                vacationRequest.ApprovedById = user.Id;
                vacationRequest.DateActioned = DateTime.Now;

                 await _requestrepo.Update(vacationRequest);
                 await _allocationrepo.Update(allocation);
                return RedirectToAction(nameof(Index), "Home");

            }
            catch (Exception ex)
            {

                return RedirectToAction(nameof(Index), "Home");
            }
          
        }

        public async Task<ActionResult> RejectRequest(int id)
        {

            try
            {
                var user = await _userManager.GetUserAsync(User);
                var vacationrequest = await _requestrepo.FindById(id);
                vacationrequest.Approved = false;
                vacationrequest.ApprovedById = user.Id;
                vacationrequest.DateActioned = DateTime.Now;

                await _requestrepo.Update(vacationrequest);
                return RedirectToAction(nameof(Index));

            }
            catch (Exception ex)
            {

                return RedirectToAction(nameof(Index));
            }
        }

        public async Task<ActionResult> CancelRequest(int id)
        {
            var vacationRequest =await _requestrepo.FindById(id);
            vacationRequest.Cancelled = true;
            await _requestrepo.Update(vacationRequest);
            return RedirectToAction(nameof(MyLeave));
        }

        public async Task<ActionResult> MyLeave()
        {
            var employee = await _userManager.GetUserAsync(User);
            var employeeid = employee.Id;
            var employeeAllocations = await _allocationrepo.GetVacationAllocationsByEmployee(employeeid);
            var employeeRequests = await _requestrepo.GetVacationRequestByEmployee(employeeid);

            var employeeAllocationsModel = _mapper.Map<List<VacationAllocationVM>>(employeeAllocations);
            var employeeRequestsModel = _mapper.Map<List<VacationRequestVM>>(employeeRequests);

            var model = new EmployeeVacationRequestViewVM
            {
                VacationAllocations = employeeAllocationsModel,
                VacationRequests = employeeRequestsModel
            };

            return View(model);
        }

        // GET: VacationRequestController/Create
        public async Task<ActionResult> Create()
        {
            var vacationtypes = await _typerepo.FindAll();
            var vacationtypeItems = vacationtypes.Select(q => new SelectListItem { 
            Text = q.Name,
            Value = q.Id.ToString()
            });
            var model = new CreateVacationRequestVM
            {
                VacationTypes = vacationtypeItems
            };
            return View(model);
        }

        // POST: VacationRequestController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateVacationRequestVM model)
        {
            var startDate = Convert.ToDateTime(model.StartDate);
            var endDate = Convert.ToDateTime(model.EndDate);
            var vacationtypes = await _typerepo.FindAll();
            var vacationtypeItems = vacationtypes.Select(q => new SelectListItem
            {
                Text = q.Name,
                Value = q.Id.ToString()
            });
            model.VacationTypes = vacationtypeItems;
            try
            {
               if(!ModelState.IsValid)
                {
                    return View(model);
                }

               if(DateTime.Compare(startDate,endDate) > 1)
                {
                    ModelState.AddModelError("", "Start Date cannot be further in the fiuture than the End Date...");
                    return View(model);
                }

                var employee = await _userManager.GetUserAsync(User);
                var allocation = await _allocationrepo.GetVacationAllocationsByEmployeeAndType(employee.Id, model.VacationTypeId);
                int daysRequested = (int)(endDate - startDate).TotalDays;

                if(daysRequested > allocation.NumberOfDays)
                {
                    ModelState.AddModelError("", "You don't have sufficient days for this request...");
                    return View(model);
                }

                var VacationRequestModel = new VacationRequestVM
                {
                    RequestingEmployeeId = employee.Id,
                    StartDate = startDate,
                    EndDate = endDate,
                    Approved = null,
                    Cancelled = false,
                    DateRequested = DateTime.Now,
                    DateActioned = DateTime.Now,
                    VacationTypeId = model.VacationTypeId
                };

                var vacationrequest = _mapper.Map<VacationRequest>(VacationRequestModel);
                var isSuccess = await _requestrepo.Create(vacationrequest);

                if(!isSuccess)
                {
                    ModelState.AddModelError("", "Something went wrong when submitting your record...");
                    return View(model);
                }

                return RedirectToAction(nameof(MyLeave));
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", "Something went wrong...");
                return View(model);
            }
        }

        // GET: VacationRequestController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: VacationRequestController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: VacationRequestController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: VacationRequestController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

CoreLeaveSystem/Controllers/VacationTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using CoreLeaveSystem.Contracts;
using CoreLeaveSystem.Data;
using CoreLeaveSystem.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace CoreLeaveSystem.Controllers
{
    [Authorize(Roles ="Administrator")]
    public class VacationTypesController : Controller
    {
        private readonly IVacationTypeRepository _repo;
        private readonly IMapper _mapper;

        public VacationTypesController(IVacationTypeRepository repo, IMapper mapper)
        {
            _repo = repo;
            _mapper = mapper;
        }
        // GET: VacationTypesController
        public async Task<ActionResult> Index()
        {
            var vacationtypes = await _repo.FindAll();
            var model = _mapper.Map<List<VacationType>, List<VacationTypeVM>>(vacationtypes.ToList());
            return View(model);
        }

        // GET: VacationTypesController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var isExists = await _repo.isExists(id);
            if(!isExists)
            {
                return NotFound();
            }
            var vacationType = _repo.FindById(id);
            var model = _mapper.Map<VacationTypeVM>(vacationType);
            return View(model);
        }

        // GET: VacationTypesController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: VacationTypesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(VacationTypeVM model)
        {
            try
            {
                if(!ModelState.IsValid)
                {
                    return View(model);
                }
                var vacationType = _mapper.Map<VacationType>(model);
                vacationType.DateCreated = DateTime.Now;
                var isSuccess = await _repo.Create(vacationType);
                if(!isSuccess)
                {
                    ModelState.AddModelError("","Something Went Wrong...");
                    return View(model);
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: VacationTypesController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var isExists = await _repo.isExists(id);
            if(!isExists)
            {
                return NotFound();
            }
            var vacationtype = _repo.FindById(id);
            var model = _mapper.Map<VacationTypeVM>(vacationtype);
            return View(model);
        }

        // POST: VacationTypesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(VacationTypeVM model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(model);
                }
                var vacationType = _mapper.Map<VacationType>(model);
                var isSuccess = await _repo.Update(vacationType);
                if(!isSuccess)
                {
                    ModelState.AddModelError("", "Something Went Wrong...");
                    return View(model);
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ModelState.AddModelError("", "Something Went Wrong...");
                return View(model);
            }
        }

        // GET: VacationTypesController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            var vacationtype = await _repo.FindById(id);
            if (vacationtype == null)
            {
                return NotFound();
            }
            var isSuccess = await _repo.Delete(vacationtype);
            if (!isSuccess)
            {
                ModelState.AddModelError("", "Something Went Wrong...");
                return BadRequest();
            }
            return RedirectToAction(nameof(Index));
        }

        // POST: VacationTypesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, VacationTypeVM model)
        {
            try
            {
                var vacationtype = await _repo.FindById(id);
                if(vacationtype == null)
                {
                    return NotFound();
                }
                var isSuccess = await _repo.Delete(vacationtype);
                if (!isSuccess)
                {
                    ModelState.AddModelError("", "Something Went Wrong...");
                    return View(model);
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

CoreLeaveSystem/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using CoreLeaveSystem.Data
@inject SignInManager<Employee> SignInManager
@inject UserManager<Employee> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Core Leave System</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Core Leave System</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="VacationRequest" asp-action="Create">Apply for Leave</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="VacationRequest" asp-action="MyLeave">My Leave</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            if (User.IsInRole("Administrator"))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Manage
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                        <a class="dropdown-item" asp-controller="VacationAllocation" asp-action="ListEmployees">Employees</a>
                                        <a class="dropdown-item" asp-controller="VacationRequest" asp-action="Index">Vacation Requests</a>
                                        <a class="dropdown-item" asp-controller="VacationTypes" asp-action="Index">Vacation Types</a>
                                        <a class="dropdown-item" asp-controller="VacationAllocation" asp-action="Index">Vacation Allocations</a>

                                    </div>
                                </li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - Core Leave System - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="//cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>